### ISSUE TITLE
Додати переклад за допомогою Google Translate REST API

### ISSUE THREAD

**Issue by webenot** [webenot/homepage#34]

**Comment by volodymyr-kushnir** [comment]
Для початку просто лінка на перекладену версію зійде — [🇷🇺 **RUSSIAN**](https://translate.google.com/translate?sl=auto&tl=ru&u=https%3A%2F%2Fwebenot.github.io%2Fhomepage%2F).

**Comment by webenot** [comment]
Дякую, я і не знала, що так можна :)) А я з API розібралася, скоро впроваджу :))
