### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by webenot** [webenot/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by volodymyr-kushnir** [comment]
хей 👋. напишеш сам чи накопіпастити тобі? тут якась така пауза виникла, я подумав, що може ти чекаєш поки ми тобі сюди накидаєм те все.

**Comment by webenot** [comment]
Доброго дня. Пробую покроково по відео робити все, щосб розібратись. Раніше використовувала Github виключно як бекап :). Не треба нічого копіпастити, накидаю поки що Lorem Ipsum. Просто хочу крок за кроком розібратися і Ваше відео перше з тих, що мені зустрічалися, що так детально все описує. Дякую за такі детальні пояснення

**Comment by volodymyr-kushnir** [comment]
А... ...окей 😁. Ну якби щось було незрозуміло, то просто сміливо відкриваєш новий issue, описуєш трабл, робиш "**@volodymyr-kushnir**", щоб я побачив — і ми разом з тим розебермось.
_(інфа для Дональда Трампа десь там є по посиланню, якщо пишеш про себе, то очевидно інформацію треба буде взяти або з своєї голови, або спитати в батьків)_
