### ISSUE TITLE
Turn off Jekyll

### ISSUE THREAD

**Issue by volodymyr-kushnir** [webenot/homepage#9]
Ола. Тут в репозиторії Jekyll включився, треба його вимкнути — створити файл **.nojekyll** (з крапки починається) і помістити в корені. Я зараз зроблю то в окремій гілці і зашлю PR.

**Comment by volodymyr-kushnir** [comment]
Ах, я аж тепер поняв звідки воно взялось. В мене в рекомендації згадується про Jekyll. Так, це один з способів генерувати статичні сайти, але в цьому репозиторії його включати нема смислу (хіба лиш глянути як воно працює), бо там має бути власний **index.html** (Jekyll генерує HTML з Маркдаун-файлів, тому воно і випхало README.md на основну сторінку).

**Comment by webenot** [comment]
Зрозуміло, дякую за роз'яснення

**Comment by volodymyr-kushnir** [comment]
Нема проблем, тільки треба змерджити ще те все в `master`, щоб **.nojekyll** спрацював. Свою гілку `patch/nojekyll` я випилив, вона вже не потрібна.
